name: fsltest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use node version 15.5.1
      uses: actions/setup-node@v3
      with:
        node-version: 15.5.1
    - run: npm install
    - run: npm run lint
    - run: npm run prettier
    - run: CI=true npm run test
    - run: npm run build

    - name: Docker ECR
      uses: appleboy/docker-ecr-action@v0.0.3
      with:
        access_key: ${{ secrets.access_key }}
        secret_key: ${{ secrets.secret_key }}
        registry: ${{ secrets.registry }}
        region: us-west-2
        repo: fsltest
        tags: latest
